### PR TITLE
Nuget packages and Custom properties

### PR DESCRIPTION
**Pull request by iremmats**
Upgraded nuget packages to latest versions.

Instead of setting "Type" : "Serilog" as only property you can now add a dictionary to allow multiple custom properties.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hi - thanks for the PR, and sorry this slipped under the radar! Unfortunately this sink is in need of some maintenance.

If you're still using this and interested in contributing please let me know, I can help get this merged, but will need assistance with documentation and testing as I am not up-to-date with where this package stands vs current APIs.

Thanks again, and sorry again about the silence! :-)

Nick

**Comment by vip32** [comment]
hi @nblumhardt , what needs to be done to get this working with the latest serilog (2.5.0)?

**Comment by nblumhardt** [comment]
Hi @vip32 - I'm not completely sure; I think it'll just be project/build-system work. https://github.com/serilog/serilog-sinks-file is a good template for how _appveyor.yml_, _Build.ps1_ and the .csproj will need to look, if you're interested in taking a shot at it 👍

**Comment by nblumhardt** [comment]
@vip32 https://www.nuget.org/packages/Serilog.Sinks.AzureEventHub/4.0.0-dev-00024 :-) 👍

**Comment by nblumhardt** [comment]
@iremmats closing this due to the long delay, apologies again for the lack of responsiveness; now that the solution is upgraded to the latest Serilog and dotnet tooling, we should be back in business for accepting PRs. Let me know if you're still keen to pursue this one. Cheers!

**Pull request closed without merging**
