### PR TITLE
Changed round bracket to square bracket in Serilog dependency (nuspec)

### PR DESCRIPTION
**Pull request by pgrejc**
In the current version of the Serilog.Sinks.AzureEventHub.nuspec file it is not possible to install the NuGet package. Dependency in the nuspec file requires Serilog version greater than or equal to 1.4.204 and lower than 2.0.0, but at the same time Serilog.Sinks.PeriodicBatching depends on Serilog greater than or equal to 2.0.0. Moreover, last commit updated Serilog to 2.0.0.

serilog sinks azureeventhub_dependency

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for the PR!

Although the tests pass, the binary won't work with Serilog 2 as far as I can tell because it's dependent on `PeriodicBatchingSink`. In Serilog 2.0, this moved from the _Serilog_ package out to _Serilog.Sinks.PeriodicBatching_. The CI process (via NuGet) will be pulling Serilog 1.x as generally NuGet chooses the lowest matching dependency version.

I think the best way to move forward on this is to 1. update the major version of this package (I can do that through AppVeyor) and 2. make the packages.config dependency an exact match on the latest released Serilog version, including any of the other packages required.

Doing:

```
Update-Package Serilog
Install-Package Serilog.Sinks.PeriodicBatching
```

Should cover everything. Keen to give it a shot?

Cheers,
Nick

**Comment by pgrejc** [comment]
`Serilog.Sinks.PeriodicBatching` is already in the _packages.config_ file, it is just not explicitly set as a dependency in the _Serilog.Sinks.AzureEventHub.nuspec_ file.

> I think the best way to move forward on this is to 1. update the major version of this package (I can do that through AppVeyor) and 2. make the packages.config dependency an exact match on the latest released Serilog version, including any of the other packages required.

That sounds like a very good plan, of course starting with 2. first. Should I do it?

**Comment by nblumhardt** [comment]
Sounds good! Yes please.

**Comment by nblumhardt** [comment]
:+1: thanks!

**Comment by pgrejc** [comment]
You're welcome. My pleasure :)

**Pull request merged**
