### PR TITLE
5.0.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #19 - remove service bus reference (@sgissinger)
 * #20 - update dependencies, extend support to .NET 4.5.1 (@DavisNT)

### CODE REVIEW

**Comment by nblumhardt** [comment]
@DavisNT is the prerelease (5.0.0-dev-*) version of the package currently working for you?

**Comment by DavisNT** [comment]
@nblumhardt The 5.0.0-dev-00048 NuGet package is working in my environment.

**Comment by nblumhardt** [comment]
Thanks @DavisNT 👍

**Comment by DavisNT** [comment]
@nblumhardt Thank you as well! :slightly_smiling_face:

**Pull request merged**
