### PR TITLE
New textFormatter initialization parameter

### PR DESCRIPTION
**Pull request by evgenyb**
Hi, 

I came across that I need to send logs to the event hub in json format and should be able to include Formatted message "field" (basically exactly the same way I can configure RollingFileSink).

### CODE REVIEW

**Comment by jonslo** [comment]
+1

**Comment by nblumhardt** [comment]
Hi @evgenyb - thanks for the PR! Sorry about the slow response (cheers @jonslo :-))

This sounds good; the rolling file sinks and others that support this use a separate overload for the formatter, however. When a formatter is specified, `outputTemplate` and `formatProvider` don't need to be.

Generally the convention is that the method accepting a formatter has it as the first argument, and skips the two parameters mentioned above.

Best regards,
Nick

**Comment by evgenyb** [comment]
Hi Nick,

Thank you for the feedback.
Added 2 new overwrite methods with formatter as a first argument.

**Comment by nblumhardt** [comment]
Thank you @evgenyb 👍

**Pull request merged**
